name: Manually Triggered Workflow

on:
    workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Say Something
        run: |
          echo "We did it"
      - name: printVar
        run: |
            echo VARIABLES $TEST_VARIABLE
