name: Manually Triggered Workflow

on:
  # push:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      environment:
      description: The name of the GitHub environment
      type: string
      default: test
env:
  env_var: ${{ vars.TEST_VARIABLE }}

jobs: 
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Say Something
        run: |
          echo "We did it"
      - name: printVar
        env:
          RIKOO: env_var
        run: |
            echo "variable from shell environment : $env_var"
