name: Manually Triggered Workflow

on:
  push:
    branches: [ "main" ]

  # workflow_dispatch:

jobs: 
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Say Something
        run: |
          echo "We did it"
      - name: printVar
        run: |
            echo "VARIABLES $TEST_VARIABLE"
