# This is a basic workflow to help you get started with Actions

name: CI Playground

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  node_env: ${{ vars.NODE_ENV }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: prod # tels from which environment to take the 'vars' and the 'secrets' from
    runs-on: ubuntu-latest
    name: Node 18
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - name: Set env
        run: |
          pwd
          echo "${{vars.NODE_ENV}}"
          echo "workflow node env: $node_env"
          echo "NODE_ENV=${{vars.NODE_ENV}}" >>  $GITHUB_ENV
          echo "AUTH_TOKEN=${{secrets.MY_SECRET}}" >>  $GITHUB_ENV
      - run: npm run whoami
      - run: npm run do:sum
      # - run: npm test
      
          
        